- src: https://github.com/websoft9dev/role_common
  version: master

- src: https://github.com/websoft9dev/role_cloud
  version: master

- src: https://github.com/websoft9dev/role_redis
  version: master

- src: https://github.com/websoft9dev/role_end
  version: master