- src: https://github.com/websoft9/role_common

- src: https://github.com/websoft9/role_cloud

- src: https://github.com/websoft9/role_nginx

- src: https://github.com/websoft9/role_redis

- src: https://github.com/websoft9/role_init

- src: https://github.com/websoft9/role_preend

- src: https://github.com/websoft9/role_end
